site_name:           DynamicalBilliards.jl
repo_url:            https://github.com/Datseris/DynamicalBilliards.jl
site_description:    An easy-to-use, modular and extendable Julia package for Dynamical Billiard systems in two dimensions.
site_author:         George Datseris
theme:               'material'

extra:
  palette:
    primary: 'deep purple'
    accent: 'cyan'
  social:
    - type: 'github'
      link: 'https://github.com/Datseris/DynamicalBilliards.jl'

markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - codehilite
  - extra
  - tables
  - fenced_code

extra_css:
  - assets/Documenter.css

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

docs_dir: 'build'

pages:
- Introduction: index.md
- Basic Usage: basic/basic_usage.md
- Tutorials:
  - Defining a Billiard Table: tutorials/billiard_table.md
  - Ray-Splitting: tutorials/ray-splitting.md
  - Visualizing: tutorials/visualizing.md
  - Creating your own Obstacle: tutorials/own_obstacle.md
  - Examples: tutorials/examples.md
- Library: basic/library.md
- Physics: physics.md
- Lyapunov Exponents: lyapunovs.md
